---

- name: install mysql repo rpm from a remote repo
  yum:
    name: https://dev.mysql.com/get/mysql80-community-release-el6-1.noarch.rpm
    state: present

- name: disable other mysql repo
  shell: yum-config-manager --disable mysql55-community mysql57-community mysql80-community

- name: enable specific mysql repo
  shell: yum-config-manager --enable mysql56-community

- name: Install MySQL
  yum: name={{ item }} update_cache=yes  state=present
  with_items:
  - mysql-devel
  - python-devel
  - MySQL-python
  - mysql-server
  - python-pip

- name: Installing pip dependencies
  pip:
    name: MySQL-python
    extra_args: --index=https://pypi.python.org/pypi/

- name: Start the MySQL service
  service:
    name: mysqld
    state: started
    enabled: true

- name: Add .my.cnf
  template: src=my.cnf.password.j2 dest=/root/.my.cnf owner=root group=root mode=0600

- name: Set root Password
  mysql_user: login_password={{ mysql_root_password }} check_implicit_admin=yes name=root host={{ item }} password={{ mysql_root_password }} state=present
  with_items:
    - localhost
    - 127.0.0.1
    - ::1

- name: Reload privilege tables
  command: 'mysql -ne "{{ item }}"'
  with_items:
    - FLUSH PRIVILEGES
  changed_when: False

- name: Remove anonymous users
  command: 'mysql -ne "{{ item }}"'
  with_items:
    - DELETE FROM mysql.user WHERE User=''
  changed_when: False

- name: Disallow root login remotely
  command: 'mysql -ne "{{ item }}"'
  with_items:
    - DELETE FROM mysql.user WHERE User='root' AND Host NOT IN ('localhost', '127.0.0.1', '::1')
  changed_when: False

- name: Remove test database and access to it
  command: 'mysql -ne "{{ item }}"'
  with_items:
    - DROP DATABASE IF EXISTS test
    - DELETE FROM mysql.db WHERE Db='test' OR Db='test\\_%'
  changed_when: False

- name: Reload privilege tables
  command: 'mysql -ne "{{ item }}"'
  with_items:
    - FLUSH PRIVILEGES
  changed_when: False
