---

- name: ensure my.cnf file configuration
  template:
    src: my.cnf.j2
    dest: /etc/my.cnf
    mode: 0644
    owner: root
    group: root

- name: restart mysqld service
  service:
    name: mysqld
    state: restarted

- name: Create wiki user and provide remote access for it
  command: 'mysql -ne "{{ item }}"'
  with_items:
    - CREATE USER wiki@'%' IDENTIFIED BY '{{ wiki_password }}';
    - CREATE DATABASE wikidatabase; 
    - GRANT ALL PRIVILEGES ON *.* TO wiki@'%' IDENTIFIED BY '{{ wiki_password }}' WITH GRANT OPTION;
    - FLUSH PRIVILEGES;
